[package]
name = "diao-na-xing"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.2", features = ["desktop"] }
dioxus-desktop = "0.2"
gloo-storage = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"